### ISSUE TITLE
nuvla lacks ability of copying resources

### ISSUE THREAD

**Issue by konstan** [nuvla/ui#247]
Benefits: forking, quick experimentations.

**Comment by schaubl** [comment]
I would add:
- move (for modules)
- export
- import

**Comment by mebster** [comment]
Let's start with copy/clone modules.

**Comment by mebster** [comment]
Working on the feature, one question is: "on the newly created module what do we do with the history?"
- Do we reset it?
- Do we keep it?
- Do we insert a new commit regarding the pasted module?

**Comment by 0xbase12** [comment]
By history I think you mean the versions map in module resource. The response to the question is we should reset it because the versions map is used by the server as metadata (it's a server-managed field) to delete specific versions or to retrieve them. If we allow to clone the versions map, if someone delete a specific version in his module, the other module is impacted.

So reset of versions is already done on module add in api-server.

The server reset the value of versions to 
```
[(cond-> {:href   content-id, :author author}
         commit (assoc :commit commit))]
```

I suggest to put a commit message with a message cloned from `module/uuid`

**Comment by 0xbase12** [comment]
https://github.com/SixSq/tasklist/issues/1937
