### ISSUE TITLE
Improvements on VPN client creation

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#271]
Fill name and description with reasonable default:
- Name: My VPN Client credential
- Description: VPN client for my user

The default VPN client should be selected.  Currently, it gives the impression it is, but it isn't.

**Comment by mebster** [comment]
On the "Generated credential" dialog, add a message, saying something like: "Please save this file, since Nuvla will not save it (it's your secret!). Go to docs.nuvla.io for details on how to configure your OpenVPN client".

**Comment by mebster** [comment]
Default name could be: "My VPN Client credential", and if with that name already exists, default to "My VPN Client credential (1)" where the number corresponds to the number of credentials with a name starting with "My VPN Client credential" minus 1.

**Comment by schaubl** [comment]
I would suggest the following syntax for the ...: 
- _name_: `<vpn server infrastructure service name> - <user username or email>`
- _description_: `<vpn server is name> credential for <user username or email>`
 
So for Toto it would be:
- _name_: 
`SixSq Customer VPN - Toto` or 
`SixSq Customer VPN - toto@example.com`
- _description_: 
`SixSq Customer VPN credential for Toto` or 
`SixSq Customer VPN credential for toto@example.com`

A user cannot have more than one VPN credential per VPN server so with this syntax there is no need for a number.

I would use the `username` (and not the `email`) because it is unique and anyway if the user created his account through the registration process, it's username will be it's email address.

Maybe (on the "new VPN" dialog) we should not show the `name` and `description` fields at all or show only the `description` so that we softly "enforce" the syntax even if the user can still update these fields afterward.
