### ISSUE TITLE
Facilitate development by allowing users (Clara) to reload a container

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#311]
As users change an app, having the ability to "apply" or "redeploy" container definitions would speed up the change/save/deploy/test cycle.

**Comment by schaubl** [comment]
_[to easily find the issue: "rerun" or "relaunch"]_

**Comment by konstan** [comment]
Another incentive for this implementation is to allow users to re-run deployment with the same data defined on the stopped deployment. So, one doesn't have to each time go via "Open With..." with data set etc.

**Comment by mebster** [comment]
The 're-launch' button should open the 'launch' modal with the parameters pre-filled as per the deployment we re-launch.

**Comment by 0xbase12** [comment]
Deployment is created on api-server with cimi add operation. 
It support only creation from pointing a module. 
To support relaunch we need to support creation from pointing to another deployment. 
Server will check if user is pointing to a deployment visible to the user with view-data right.

There is attributes stored in the deployment that should be cleaned-up like : 
parent (credentials)
api-key
perhaps should we keep data maps @konstan

**Comment by konstan** [comment]
I believe we are discussing lunching new deployment based on the current one - either running or stopped. Right?
Just to note that this contradicts with the wording of the issue `Facilitate development by allowing users (Clara) to reload a container` - which for me means update the currently running deployment by re-loading/starting container(s) behind it.

Irrespective to that though and in both cases from above - @0xbase12 yes, we should keep data maps.

**Comment by 0xbase12** [comment]
Yes you are right @konstan we are discussing 2 things in this ticket:
- update a running deployment definition and relaunch (e.g. edit docker-compose, files, etc.)
- redeploy - create a new deployment from another one by keeping params of the base deployment

**Comment by schaubl** [comment]
@0xbase12 for the redeploy why not creating the new deployment by pointing to the module used to create the current deployment ?
In this case there is no need for changes api-server side.

I'm suggesting this to try to keep the implementation as simple as possible but maybe it's cleaner to do it server side.

**Comment by 0xbase12** [comment]
@schaubl doing that is more complicated because server take only the url of the module and do the process to retrieve it and create a deployment from it. 

So if we do that, UI will have to create a deployment from module url that can be latest or a specific version. **Problem 1**: In case of latest, module could have diverged from the current deployment.
Consider it hasn't diverged. UI have to create a new deployment from module / update the created deployment to match the current deployment / allow user only after edition success to update it at his turn. **Problem 2**: The UI implementation is more complicated and current implementation will change a lot I think to allow that.
**Problem 3**: it's not reusable and each client have to implement this workflow.

**Comment by mebster** [comment]
For re-deploy, I think a clean server-side solution makes more sense, and then the feature is available via the API.

I would carve the 'docker apply' feature from this one (or the other way around).  But it's also very useful, especially during development.

**Comment by schaubl** [comment]
@0xbase12 you mentioned an interesting question which is: 
"Which module version to deploy when redeploying ?"

I think, ideally the user should be able to choose.
If not possible or too complicated, I would suggest the latest version.
Because IMHO I think this will be the most popular scenario.

For example you create an app, you deploy it but it doesn't work as expected and you have to fix the app definition and then you need to redeploy with the same parameters.
Another usage of this feature would be to redeploy to update an app to the latest definition (ie: docker compose file).

**Comment by 0xbase12** [comment]
How should we name the action on `Deployment` resource to fetch last version of module used at creation time and apply changes:
- Redeploy
- Apply
- Restart
- Module-update
- ... 
To refresh module of a started deployment: Update / Apply /

**Comment by konstan** [comment]
If I understand correctly then it's Restart for me.

My understanding. 
When deployment is in `STARTED` or `ERROR`, Restart button becomes available. By clicking on Restart, Nuvla takes the latest version of the module the deployment was started with, merges it into the current deployment. User is presented with a modal to edit params and confirm the action. Parameters are merged and values chosen for the running deployment take precedence. Then, Nuvla runs IS specific `apply` action on the current deployment on the same Creds(+IS). User can't change Creds(+IS).

Is this correct?

**Comment by konstan** [comment]
With the above Restart, user should be given a choice of using potentially new `latest` module version or keep the current one.

**Comment by 0xbase12** [comment]
### Clone
  - Only source Deployment is used to create a new Deployment. Module, files, env, data are the same.
  - Source Deployment is not touched at all and continue his normal lifecycle.
  - User has the choice to select another cloud, edit files, env, data in the deployment modal phase

### Apply/redeploy,...
  - Operation is available to Deployment in state STARTED or ERROR
  - Operation request body have option `fetch-module` with default value to false
  - If fetch-module is false, current module is kept else module href is resolved and we keep values of env if they still exist in the new module, else they are deleted, same for files
  - User has the choice to edit current env and files
  - Deployment is stopped, deployment parameters are deleted and recreated and finally deployment is started
