### ISSUE TITLE
Nuvlabox update modal warnings

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/ui#525]
User need to be careful when updating from an old (<1.14.0). This is because the NBE installation uses plenty of environment variables. From 1.14.0 onwards, those runtime env vars are published to Nuvla, so that the update job can take them for the update action. But if you have an older NBE version, those env vars won’t be there, which means the update job will try to infer them (in fact it is the nuvlabox/installer who tries to infer this). So success is not guaranteed on those situations.

**Comment by 0xbase12** [comment]
@cjdcordeiro Your message about may not work is clear. Do you have more instructions about a recovery steps? Should user save env variables in case of an issue occurs? Reinstall completely the box and deleting the volumes, deployments etc.

**Comment by cjdcordeiro** [comment]
@0xbase12 the fix should be on our side. The action should accept those params from the user.

but since we don't have that, it is really hard to advice, cause it would be impossible to infer the final state after the update, even if successful. Worst case scenario, the user has to go into the NB, re-export the initial env vars, and re-do the `up` command used for installing the nbe

**Comment by 0xbase12** [comment]
Waiting on https://github.com/nuvla/documentation/issues/56
