### ISSUE TITLE
Deployment shows ERROR in docker-compose using environment variables in ports section

### ISSUE THREAD

**Issue by dgasull** [nuvla/ui#654]
If I specify in docker-compose a service with ports as environment variables:
```
    ports:
      - ${DSPYTHON_PORT:-6867}:${DSPYTHON_PORT:-6867}
``` 

UI shows "ERROR" even if it is actually working in the edge:

```
Exception: The Compose file '/tmp/tmpisrk06pw/docker-compose.yaml' is invalid because:
services.dspython.ports contains an invalid type, it should be a number, or an object
```

Then `Job start_deployment failed` appears

**Comment by cjdcordeiro** [comment]
@dgasull can u pls provide a screenshot of both app and deployment pages in the UI?

**Comment by dgasull** [comment]
Sure! Start deployment error:

![Screenshot from 2021-06-22 17-09-22](https://user-images.githubusercontent.com/38685890/122950989-36e0b180-d37d-11eb-82b2-c0f25a1f7f77.png)

But services are properly deployed in edge: 

![Screenshot from 2021-06-22 17-09-31](https://user-images.githubusercontent.com/38685890/122951089-4d870880-d37d-11eb-847f-c7c6eded9bde.png)

Finally, if I try to stop the deployment, also an error appears: 

![Screenshot from 2021-06-22 17-10-44](https://user-images.githubusercontent.com/38685890/122951182-61cb0580-d37d-11eb-804e-3584eb7e3178.png)
![Screenshot from 2021-06-22 17-11-28](https://user-images.githubusercontent.com/38685890/122951197-655e8c80-d37d-11eb-8fa3-8c82ac104f96.png)

**Comment by cjdcordeiro** [comment]
yep that should be enough thanks!

I'm asking @0xbase12 to have a look at this

**Comment by 0xbase12** [comment]
*The issue is not related to UI but for job processor.*

## For the start action failure
Job execution is happen successfully during the `docker-compose up` command. This is why the application is running correctly even if later a failure occur.

The failure is happening during the listing of created services name because the command docker-compose config services is used with the `--no-interpolate` option. This option mean "Don't interpolate environment variables"

Question to you @cjdcordeiro, is there a reason to use this option while listing the services?
https://github.com/nuvla/job-engine/blob/2.15.2/code/src/nuvla/connector/docker_compose_cli_connector.py#L179

## For the stop action failure
Simply the command `docker-compose down` command is run by the job executor. Job executor run the command and wait max 2 minutes before timeouting. Usually this is application related.

**Comment by cjdcordeiro** [comment]
@0xbase12 I believe the `--no-interpolate` is there to make sure only the yaml file is printed, for easier parsing, otherwise other things (like WARNINGS for unset env vars, or Swarm mode suggestions) will be printed alongside the yaml file
