### ISSUE TITLE
Removing component for which to get log triggers an error message

### ISSUE THREAD

**Issue by mebster** [nuvla/ui#871]
Found during testing dojo 06/09/2022

**Comment by mebster** [comment]
Once we start fetching logs, removing the component triggers an error.
<img width="1366" alt="Screenshot 2022-09-06 at 15 50 56" src="https://user-images.githubusercontent.com/419519/188654584-12a75f93-b27b-4329-8b17-51ac80040d0d.png">
<img width="1299" alt="Screenshot 2022-09-06 at 15 50 44" src="https://user-images.githubusercontent.com/419519/188654613-b859c567-2044-45e8-8879-217e9dcb9747.png">

**Comment by 0xbase12** [comment]
The issue is coming because the NuvlaEdge is shared with only view rights and manage rights.

The created resource-log get his acl based on the NuvlaEdge ACL.

ACL of the Resource-log is equal to:
owners = [<id of the NuvlaEdge>]
manage= [<from NuvlaEdge acl, all that has right view-acl>]
delete= [<from  NuvlaEdge acl, all that has right delete>]

**Comment by 0xbase12** [comment]
Solution. I think this can be simplified to the following.
owners = [id of the NuvlaEdge, creator active-claim]
Since resource-log is not something to share between viewers.
